
name: prithvi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - accelerate==1.1.1
      - aenum==3.1.15
      - affine==2.4.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - albucore==0.0.16
      - albumentations==1.4.10
      - alembic==1.14.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asciitree==0.3.3
      - asttokens==2.4.1
      - attrs==24.2.0
      - bitsandbytes==0.44.1
      - blinker==1.9.0
      - Bottleneck==1.4.2
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask==2024.11.1
      - databricks-sdk==0.36.0
      - decorator==5.1.1
      - Deprecated==1.2.14
      - docker==7.1.0
      - docstring_parser==0.16
      - efficientnet_pytorch==0.7.1
      - einops==0.8.0
      - executing==2.1.0
      - fasteners==0.19
      - filelock==3.16.1
      - fiona==1.10.1
      - Flask==3.0.3
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - geopandas==1.0.1
      - gitdb==4.0.11
      - GitPython==3.1.43
      - google-auth==2.36.0
      - granitewxc @ git+https://github.com/IBM/granite-wxc.git@1d180f6d730e26fcd605925f6514f7974122f973
      - graphene==3.4.3
      - graphql-core==3.2.5
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - gunicorn==23.0.0
      - h5netcdf==1.4.0
      - h5py==3.12.1
      - huggingface-hub==0.26.2
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.36.0
      - importlib_metadata==8.5.0
      - importlib_resources==6.4.5
      - ipdb==0.13.13
      - ipython==8.29.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - Jinja2==3.1.4
      - joblib==1.4.2
      - jsonargparse==4.34.0
      - kiwisolver==1.4.7
      - kornia==0.7.4
      - kornia_rs==0.1.7
      - lazy_loader==0.4
      - lightly==1.5.14
      - lightly-utils==0.0.2
      - lightning==2.4.0
      - lightning-utilities==0.11.8
      - locket==1.0.0
      - Mako==1.3.6
      - Markdown==3.7
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mlflow==2.17.2
      - mlflow-skinny==2.17.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - munch==4.0.0
      - netCDF4==1.7.2
      - networkx==3.4.2
      - numcodecs==0.13.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - pretrainedmodels==0.7.4
      - PrithviWxC @ git+https://github.com/NASA-IMPACT/Prithvi-WxC.git@ecfd69b2e94b6505d3accbdecf095b92fd18411e
      - torch==2.5.0
      - torchvision==0.20.0
